Feature/island cleanup
anno-mods/AnnoMapEditor pull request #28
Opened 2022-12-18 17:31 UTC by Cyclonit

I noticed that almost all of the async/await in `Island` and `Session` is due to `Island.SizeInTiles`. It is loaded lazily and asynchronously in `Island.UpdateExternalDataAsync`. This being async propagates throughout the classes and leads to all kinds of jank.

I refactored the `IslandMapPool` to load all of the maps' sizes on initialization of the pools. This removes the necessity of most async/awaits throughout these classes.

2022-12-19 07:10 UTC, jakobharder commented on AnnoMapEditor/MapTemplates/Region.cs
> +                    IslandMap.FromFilePathTemplate("data/sessions/islands/pool/moderate/moderate_l_{0}/moderate_l_{0}.a7m", 1, 14),
Island loading takes some time, I'm not sure if it's a good idea to load all islands immediately.

2022-12-19 07:56 UTC, Cyclonit commented on AnnoMapEditor/MapTemplates/Region.cs
> +                    IslandMap.FromFilePathTemplate("data/sessions/islands/pool/moderate/moderate_l_{0}/moderate_l_{0}.a7m", 1, 14),
In my testing there is no noteworthy delay by loading them synchronously. Async and await have a tendency of spreading throughout code like a virus. To me the delay caused by loading all maps at the beginning is outweighed by the benefit of a significantly cleaner code base.

2022-12-20 16:12 UTC, Shad0wlife requested changes
> Extracted StartingSpot from Island
StartingSpots and Islands are two different kinds of entity and thus should be represented using different classes. Clean up of rendering code is not finished, but I think this is a good start.

If we extract StartingSpot, we might want to eventually also separate PoolIsland and FixedIsland or so. But we'd need to evaluate if that actually helps, or might hinder something (eg. a conversion from Pool to Fixed or the other way round - we'd need to define conversion operators or so in the worst case...) ~~And have all 3 be inherited from MapElement or so?~~ Reading helps, you already created a base class of that exact same name 😄

2022-12-20 16:12 UTC, Shad0wlife commented on AnnoMapEditor/MapTemplates/Serializing/IslandReader.cs
> +        public static async Task<int?> ReadTileInSizeFromFileAsync(string mapPath)
While I agree with the idea of using null as an error state, we will start boxing here. In my opinion it might be sufficient to use -1 (or any other negative value) as error here, since a negative value makes no sense by definition anyways.

2022-12-20 16:12 UTC, Shad0wlife commented on AnnoMapEditor/MapTemplates/Islands/IslandMap.cs
> +    public class IslandMap
I don't know if this is the right place to put this, but before, there was a TextBlock on the Map Island Items:
![grafik](https://user-images.githubusercontent.com/15235997/208712270-87b997f4-ff91-4fa5-bc01-9cf32a77be7b.png)

These are currently missing. I'd still like to keep them, and have them say something like "Large - Pool" (maybe with a newline instead of a dash). That would also give us a place to display the labels of Fixed, named islands, and display "Large - Fixed" for fixed unnamed islands for example.

We could also maybe add a toggle somewhere to hide those texts, but I'd give that a low priority.

2022-12-20 16:12 UTC, Shad0wlife commented on AnnoMapEditor/UI/Controls/MapObject.xaml.cs
> -                if (!string.IsNullOrEmpty(island.Label))
This is the title section which I talked about in IslandMap.cs, so maybe this would be the place, though a Binding to IslandMap might be better?

2022-12-20 16:12 UTC, Shad0wlife commented on AnnoMapEditor/UI/Models/SessionPropertiesViewModel.cs
> +                    _session.SetRegion(value);
This is a duplicate now. SetRegion sets the Region for the session, so manually setting it the line before doesn't do anything.

2022-12-20 16:14 UTC, Shad0wlife commented on AnnoMapEditor/MapTemplates/Islands/IslandMapPool.cs
> +                ?? throw new NullReferenceException($"Could not find map '{mapFilePath}'.");
This is what currently breaks the unit tests, as they don't load the game files, making the image file path nonexistent.

2022-12-20 21:07 UTC, Cyclonit commented on AnnoMapEditor/MapTemplates/Islands/IslandMapPool.cs
> +                ?? throw new NullReferenceException($"Could not find map '{mapFilePath}'.");
In that case we need some mocks. As discussed earlier today, we should turn to load as many data from the real files as possible.

2022-12-20 21:07 UTC, Cyclonit commented on AnnoMapEditor/UI/Models/SessionPropertiesViewModel.cs
> +                    _session.SetRegion(value);
I'll remove it.

2022-12-20 21:14 UTC, Cyclonit commented on AnnoMapEditor/UI/Controls/MapObject.xaml.cs
> -                if (!string.IsNullOrEmpty(island.Label))
Yes, I think we will clean this up as part of the refactor we talked about. We need to clean up the relationship between blueprints, map elements and UI controls in general.

2022-12-20 21:16 UTC, Cyclonit commented on AnnoMapEditor/MapTemplates/Islands/IslandMap.cs
> +    public class IslandMap
Given that my other work changes all of the controls, I would leave this as it is right now and work on this in the upcoming PR. My general opinion is such that we only use the sizes for island pools. Fixed islands should be identifiable as such.

2022-12-20 21:21 UTC, Cyclonit commented on AnnoMapEditor/MapTemplates/Islands/IslandMap.cs
> +            => FromFilePathTemplate(filePathTemplate, Enumerable.Range(0, count).ToArray());
Fixed.

2022-12-20 21:24 UTC, Cyclonit commented on AnnoMapEditor/MapTemplates/Island.cs
>          public async Task<Island> CloneAsync()
Done.

2022-12-21 18:02 UTC, Cyclonit commented on AnnoMapEditor/MapTemplates/Island.cs
>                          return null;
This should be covered in a separate PR.

2022-12-21 18:03 UTC, Cyclonit commented on AnnoMapEditor/MapTemplates/Serializing/IslandReader.cs
> +        public static async Task<int?> ReadTileInSizeFromFileAsync(string mapPath)
The underlying methods return integers. Using an integer like -1 to signal errors would mix up the behaviour of the underlying methods and our code calling it. Boxing doesn't introduce any issues here and clearly separates those affairs.

2022-12-23 17:56 UTC, Cyclonit commented
I will redo this PR.

2022-12-23 17:56 UTC, closed without merging