Fixed Fertilities and Slots
anno-mods/AnnoMapEditor pull request #49
Opened 2023-02-04 10:38 UTC by Cyclonit

2023-02-18 23:00 UTC, Shad0wlife commented
This looks like a lot of stuff. I don't know how much of a review I can do here. I'll have to play around with the features though to see if any issues or errors crop up.

2023-03-07 21:58 UTC, Shad0wlife requested changes
Very sophisticated island slot designer! Works as intended as far as I can tell (with the addition of the PR I added to this PR ;) )

2023-03-07 21:58 UTC, Shad0wlife commented on AnnoMapEditor/UI/Overlays/SelectSlots/SelectSlotsOverlay.xaml.cs
> +                newViewModel.SlotAssignmentViewModels.CollectionChanged += SlotAssignmentViewModels_CollectionChanged;
Fix found in https://github.com/Cyclonit/AnnoMapEditor/pull/3

2023-03-08 20:17 UTC, Cyclonit commented on AnnoMapEditor/DataArchives/Assets/Models/StandardAsset.cs
>          public StandardAsset(XElement valuesXml)
Good question... I think there was a reason to not make it abstract. But I cannot find it any more. I believe we can safely make it abstract.

2023-03-08 20:18 UTC, Cyclonit commented on AnnoMapEditor/DataArchives/Assets/Repositories/FixedIslandRepository.cs
> +                // First there are lists with a single item of the following form. They denote the
Gogogo ;)

2023-03-08 20:18 UTC, Cyclonit commented on AnnoMapEditor/UI/Overlays/SelectSlots/SelectSlotsOverlay.xaml.cs
> +                newViewModel.SlotAssignmentViewModels.CollectionChanged += SlotAssignmentViewModels_CollectionChanged;
Merged the PR.

2023-03-21 15:43 UTC, Shad0wlife commented on AnnoMapEditor/DataArchives/Assets/Models/StandardAsset.cs
>          public StandardAsset(XElement valuesXml)
Changed.

2023-04-07 13:26 UTC, merged